# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_path', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('memory_limit', models.FloatField()),
                ('time_limit', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('server_language', models.CharField(max_length=20)),
                ('server_path', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=260)),
                ('selected', models.BooleanField()),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Challenger')),
            ],
        ),
        migrations.AddField(
            model_name='challenger',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='challenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Challenger'),
        ),
    ]
