# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170512_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('P', 'In progress'), ('F', 'Finished')], default='Q', max_length=20),
        ),
    ]
