# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170512_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='game',
        ),
        migrations.AlterField(
            model_name='job',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
    ]
