# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170512_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='game',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='job',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
