# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170512_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('P', 'In progress'), ('F', 'Finished')], default='Q', max_length=20)),
                ('publication_date', models.DateTimeField(verbose_name='Date of publication')),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Game')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Job'),
        ),
        migrations.AddField(
            model_name='submission',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Job'),
        ),
    ]
