# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_auto_20170512_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenger',
            name='game',
        ),
        migrations.RemoveField(
            model_name='challenger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='source',
            name='challenger',
        ),
        migrations.AddField(
            model_name='source',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Challenger',
        ),
    ]
