# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170512_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengers',
            field=models.ManyToManyField(to='web.Source'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='web.Source'),
        ),
    ]
