# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170512_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Source'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Job'),
        ),
    ]
