# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170512_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='publication_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('Q', 'Queued'), ('P', 'In progress'), ('F', 'Finished')], default='Q', max_length=20),
        ),
    ]
