# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170513_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=2),
        ),
    ]
