# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_game_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='players_min',
        ),
        migrations.AddField(
            model_name='game',
            name='players_max',
            field=models.IntegerField(default=2),
        ),
    ]
