# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170513_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='result',
        ),
        migrations.AddField(
            model_name='source',
            name='result',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=20),
        ),
    ]
