# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0015_auto_20170514_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Functionality'), ('V', 'Visual'), ('S', 'Submission'), ('C', 'Challenge'), ('G', 'Game'), ('A', 'Account'), ('B', 'Security'), ('O', 'Other')], default='O', max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('T', 'Taken'), ('F', 'Finished'), ('R', 'Rejected')], default='P', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
