# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('PY2', 'Python2'), ('Cpp', 'C++')], default='PY2', max_length=20),
        ),
    ]
