# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0017_auto_20170527_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Win'), ('T', 'Tie'), ('L', 'Lost'), ('D', 'Disqualified'), ('P', 'Pending')], default='P', max_length=15)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('xp_reach', models.IntegerField()),
                ('xp_win', models.IntegerField()),
                ('xp_lost', models.IntegerField()),
                ('xp_draw', models.IntegerField()),
                ('xp_dsq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='challengers',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='log_path',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='server_language',
        ),
        migrations.RemoveField(
            model_name='game',
            name='server_path',
        ),
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='log_path',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='levelinguser',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='levelinguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='challenger',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Challenge'),
        ),
        migrations.AddField(
            model_name='challenger',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Source'),
        ),
    ]
