# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20170802_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challengers',
            field=models.ManyToManyField(through='web.Challenger', to='web.Source'),
        ),
    ]
