# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_challenge_challengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='result',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('D', 'Disqualified')], default='P', max_length=20),
        ),
    ]
