# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20170802_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
