# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_challenger_xp_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('PY2', 'Python2'), ('C', 'C')], default='PY2', max_length=20),
        ),
    ]
