# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20170911_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('C', 'C')], default='PY', max_length=20),
        ),
    ]
